import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Filter } from '@components/Filter/Filter'
import {  useAppSelector } from '../hooks/hooks'
import Repos from '@components/ReposList/ReposList'
import styles from '../styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

 
export default function Home() {
  const filteredRepo = useAppSelector(state=> state.repos.filteredList)
  return (
    <>
      <Head>
        <title>Test task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} ${styles.wrapper} `}>
        <Filter  />
        {
          filteredRepo.length> 0 ? <Repos repos={filteredRepo}/> : 
          <div className={styles.notFound}>
              Введите существующего пользователя!
          </div>
        }
      </main>
    </>
  )
}
